version: '3.8'

services:
  app:
    container_name: nest_app
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_test
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    volumes:
      - app_test_postgres:/var/lib/postgresql/data
    networks:
      - app_test

  db_test:
    container_name: postgres_db_test
    image: postgres:16.3-alpine3.20
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    networks:
      - app_test

volumes:
  app_test_postgres:


networks:
  app_test:
