version: '3.8'

services:
  app:
    container_name: nest_app
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_test
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    volumes:
      - app_test_postgres:/var/lib/postgresql/data
    networks:
      - app_test

volumes:
  app_test_postgres:


networks:
  app_test:
